spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Shanghai
  profiles:
#    active: local
#    active: test
#    active: dev
    active: pro
  mail:
    # 指定邮件服务器地址
    host: smtp.qiye.aliyun.com
    # 登录账户
    username: linux@xlike.email
    # 登录密码
    password: "1jGbVKez74jrQ5W1"
    # 端口
    port: 25
    # 默认编码
    default-encoding: UTF-8
    # 使用的协议
    protocol: smtp
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          host: smtp.qiye.aliyun.com   #阿里云
#         host: smtp.qq.com    #QQ
          port: 465
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
            port: 465
        debug: true
  application:
    name: apiAi
  config:
    import:
      - optional:application-datasource.yml
      - optional:application-web.yml
      - optional:application-redis.yml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info